apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-ml
spec:
  selector:
    matchLabels:
      app: api-ml
  template:
    metadata:
      labels:
        app: api-ml
    spec:
      containers:
        - name: api-ml
          image: adilsonsilvajr/diabetes-ml:latest
          resources:
            requests:
              memory: "2G"
            limits:
              memory: "4G"
          securityContext:
            privileged: true
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api-ml-service
spec:
  selector:
    app: api-ml
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: adilsonsilvajr/diabetes-app:latest
          resources:
            requests:
              memory: "1G"
            limits:
              memory: "2G"
          securityContext:
            privileged: true
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8501
  type: LoadBalancer
