FROM python:3.9-buster

RUN set -e; \
    apt-get update -y && apt-get install -y \
    tini \
    lsb-release; \
    gcsFuseRepo=gcsfuse-`lsb_release -c -s`; \
    echo "deb http://packages.cloud.google.com/apt $gcsFuseRepo main" | \
    tee /etc/apt/sources.list.d/gcsfuse.list; \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
    apt-key add -; \
    apt-get update; \
    apt-get install -y gcsfuse \
    && apt-get clean

RUN mkdir app && mkdir app/datasets
    
WORKDIR /app

COPY src/requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ .

ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/terraform-config.json

RUN chmod +x start.sh

EXPOSE 8501

ENTRYPOINT ["./start.sh", "start"]
